version: "3.7"

services:
  portal:
    image: jeffernz/geneweb:latest
    volumes:
      - bases:/usr/local/var/geneweb
    ports:
      - ${PORTAL_PORT}:2317
    entrypoint:
      - main.sh
      - start-portal

  setup:
    image: jeffernz/geneweb:latest
    volumes:
      - bases:/usr/local/var/geneweb
    ports:
      - ${SETUP_PORT}:2316
    entrypoint:
      - main.sh
      - start-setup

volumes:
  bases:
    driver_opts:
      type: none
      device: $HOME/GenealogyData
      o: bind