
services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bases:/geneweb
    ports:
      - ${PORTAL_PORT}:2317
    entrypoint:
      - main.sh
      - start-portal
    env_file:
      - .env
    restart: no

  setup:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - bases:/geneweb
    ports:
      - ${SETUP_PORT}:2316
    entrypoint:
      - main.sh
      - start-setup
    env_file:
      - .env
    restart: no

volumes:
  bases:
    driver_opts:
      type: none
      device: ./.geneweb_data
      o: bind