version: "3.7"

services:
  portal:
    image: jeffernz/geneweb:latest
    volumes:
      - bases:/usr/local/var/geneweb
    ports:
      - ${PORTAL_PORT}:2317
    entrypoint:
      - main.sh
      - start-portal
    env_file:
      - .env

  setup:
    image: jeffernz/geneweb:latest
    volumes:
      - bases:/usr/local/var/geneweb
    ports:
      - ${SETUP_PORT}:2316
    entrypoint:
      - main.sh
      - start-setup
    env_file:
      - .env

volumes:
  bases:
    driver_opts:
      type: none
      device: $HOME/GenealogyData
      o: bind